services:
  directus:
    image: directus/directus:11.17.4
    container_name: directus-sistema-gestion
    ports:
      - "8055:8055"
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - .env
    restart: always

